name: Coverity

on:
  push:
    branches:
      - coverity_scan

jobs:
  build:
    if: github.repository_owner == 'waffle'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Analyze with Coverity
        run: |
          wget https://scan.coverity.com/download/linux64 --post-data="token=${{ secrets.GITHUB_TOKEN }}&project=Waffle%2Fwaffle&md5=1" -O coverity_tool.md5
          unzip -j cov-analysis-linux64-*.tar.gz -d /tmp
          /tmp/cov-analysis-linux64-*/bin/cov-build --dir cov-int mvn -DskipTests=true verify
          tar czvf waffle.tgz cov-int
          curl --form token="${{ secrets.COVERITY_TOKEN}}" \
            --form email=${{ secrets.EMAIL }} \
            --form file=@waffle.tgz \
            --form version="waffle/coverity_scan" \
            --form description="Waffle Coverity Scan" \
            https://scan.coverity.com/builds?project=Waffle%2Fwaffle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}
