name: Coverity

on:
  push:
    branches:
      - coverity_scan

jobs:
  build:
    if: github.repository_owner == 'waffle'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Analyze with Coverity
        run: |
          wget -q https://scan.coverity.com/download/java/linux64
          unzip -j cov-analysis-linux64-*.tar.gz -d /tmp
          /tmp/cov-analysis-linux64-*/bin/cov-build --dir cov-int mvn -DskipTests=true verify
          tar czvf waffle.tgz cov-int
          curl --form token="${{ secrets.COVERITY_TOKEN}}" \
            --form email=jeremylandis@hotmail.com \
            --form file=@waffle.tgz \
            --form version="waffle/coverity_scan" \
            --form description="Waffle Coverity Scan" \
            https://scan.coverity.com/builds?project=Waffle%2Fwaffle
