name: Site

on:
  push:
    branches:
      - site

jobs:
  build:
    if: github.repository_owner == 'waffle'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Build site
        run: ./mvnw site site:stage -DskipTests -B --file Source/JNA/pom.xml
        env:
          CI_DEPLOY_USERNAME: ${{ secrets.CI_DEPLOY_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy Site to gh-pages
        uses: JamesIves/github-pages-deploy-action@master
        with:
          SSH: true
          BRANCH: gh-pages
          FOLDER: Source/JNA/target/staging
